In [1]:
import sys
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pylab import mpl
import json
sys.path.append('./module/')
sys.path.append('/home/zhangjianquan/anaconda3/lib/python3.7/site-packages/')

In [17]:
raw_data=pd.read_csv('../../../Data/Price_System/Price_Predict/raw/house/used_house_data_test.csv')
raw_data = raw_data.head()
raw_data

,ID,Region,Road,Community_Name,House_Type,Transaction_Time,Final_Price,Unit_Price,Listing_Price,Transaction_Cycle,...,Trading_Authority,Listing_Time,Housing_Purposes,House_Ownership,Year_Of_Housing,Storey,Ladder,Household,Num_Bedroom,Num_Hall
0,107100261662,浦东,三林,城林雅苑,1室1厅,2018-09-30,218.0,46502.0,235.0,149.0,...,动迁安置房,2018-05-05,普通住宅,非共有,NaN,28.0,1.0,6.0,1.0,1.0
1,107100668755,浦东,源深,盛世年华,3室2厅,2018-09-30,1620.0,107613.0,1680.0,8.0,...,商品房,2018-09-23,普通住宅,共有,NaN,32.0,2.0,2.0,3.0,2.0
2,107100566972,浦东,世博,雪野二村,2室1厅,2018-09-30,368.0,62089.0,380.0,43.0,...,商品房,2018-08-19,普通住宅,非共有,NaN,6.0,1.0,4.0,2.0,1.0
3,107100390003,浦东,周浦,印象春城,2室2厅,2018-09-30,368.0,41242.0,388.0,105.0,...,商品房,2018-06-18,普通住宅,NaN,NaN,18.0,2.0,4.0,2.0,2.0
4,107100382965,浦东,康桥,双秀西园,2室2厅,2018-09-30,289.0,36125.0,310.0,108.0,...,动迁安置房,2018-06-15,普通住宅,共有,NaN,11.0,1.0,4.0,2.0,2.0

In [3]:
from main_predict import price_predict
encoder_path='../../../output/Price_System/Price_Predict/results/encoder.csv'
path_standModel='../../../output/Price_System/Price_Predict/model/stand.pkl'
path_stand_feature='../../../output/Price_System/Price_Predict/results/featureOrder.txt'
path_select_feature='../../../output/Price_System/Price_Predict/results/feature.json'

In [15]:
# fr = open(path_select_feature, 'r', encoding='UTF-8')
# cols = json.load(fr)
# fr.close()
# feature = []
# for k in cols.keys():
#     for i in cols[k]:
#         feature.append(i)
# print(feature,len(feature))
# diff = set(raw_data.columns).difference(set(feature))
# raw_data.drop(diff, axis=1, inplace=True)
# raw_data

['Transaction_Cycle', 'Num_Look', 'Num_Browse', 'Age', 'Ladder', 'Longitude', 'House_Type', 'Elevator', 'House_Ownership', 'Oriented', 'Unit_Structure', 'Construction_struct'] 12

,House_Type,Transaction_Cycle,Num_Look,Num_Browse,Unit_Structure,Oriented,Age,Construction_struct,Elevator,House_Ownership,Ladder
0,1室1厅,149.0,4,1565.0,NaN,南,2013.0,钢混结构,有,非共有,1.0
1,3室2厅,8.0,4,252.0,NaN,南,2005.0,钢混结构,有,共有,2.0
2,2室1厅,43.0,1,NaN,平层,南,1986.0,砖混结构,无,非共有,1.0
3,2室2厅,105.0,18,6048.0,平层,南,2011.0,钢混结构,有,NaN,2.0
4,2室2厅,108.0,0,2956.0,平层,南,2008.0,钢混结构,有,共有,1.0

In [18]:
cols = {}
cols['num'] = ['Final_Price','Transaction_Cycle','Num_Price_Adjustment',
                'Num_Look', 'Attention', 'Num_Browse', 'Construction_Area','Age','Storey', 'Ladder', 'Household','Year_Of_Housing',
                'Property_Rights_Time']
cols['str'] = list(set(list(raw_data.columns)).difference(set(cols['num'])))

35